name = "telegram-message-forward-bot"
type = "javascript"
account_id = ""
workers_dev = true

[[kv_namespaces]]
binding = "LOGS"
id = ""
preview_id = ""

[dev]
port = 8080

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
